
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Quote, UserSettings } from '../types';

// Removed the 'jspdf' module augmentation as it was causing resolution errors.
// Using the functional autoTable(doc, options) approach instead.

export const pdfService = {
  generateQuotePDF: async (quote: Quote, settings: UserSettings) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(24);
    doc.setTextColor(40);
    doc.text('QUOTE', 14, 25);
    
    doc.setFontSize(10);
    doc.text(`Quote #: ${quote.number}`, 14, 32);
    doc.text(`Date: ${new Date(quote.date).toLocaleDateString()}`, 14, 37);
    doc.text(`Valid Until: ${new Date(quote.validUntil).toLocaleDateString()}`, 14, 42);

    // Company Info (Right Aligned)
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(settings.companyName, pageWidth - 14, 25, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const addressLines = settings.companyAddress.split('\n');
    let y = 30;
    addressLines.forEach(line => {
      doc.text(line, pageWidth - 14, y, { align: 'right' });
      y += 5;
    });
    doc.text(settings.companyEmail, pageWidth - 14, y, { align: 'right' });
    doc.text(settings.companyPhone, pageWidth - 14, y + 5, { align: 'right' });

    // Customer Info
    y = 60;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('BILL TO:', 14, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(quote.customer.name, 14, y + 7);
    if (quote.customer.company) doc.text(quote.customer.company, 14, y + 12);
    if (quote.customer.email) doc.text(quote.customer.email, 14, y + 17);
    if (quote.customer.phone) doc.text(quote.customer.phone, 14, y + 22);
    if (quote.customer.address) {
      const custAddrLines = quote.customer.address.split('\n');
      custAddrLines.forEach((line, i) => {
        doc.text(line, 14, y + 27 + (i * 5));
      });
    }

    // Line Items Table
    const tableRows = quote.items.map(item => [
      item.name + (item.description ? `\n${item.description}` : ''),
      item.quantity,
      `$${item.price.toFixed(2)}`,
      item.discountValue > 0 ? `${item.discountValue}${item.discountType === 'percentage' ? '%' : '$'}` : '-',
      `$${((item.price * item.quantity) - (item.discountType === 'percentage' ? (item.price * item.quantity * item.discountValue / 100) : item.discountValue)).toFixed(2)}`
    ]);

    // Use autoTable functional API
    autoTable(doc, {
      startY: 110,
      head: [['Description', 'Qty', 'Unit Price', 'Disc', 'Total']],
      body: tableRows,
      theme: 'striped',
      headStyles: { fillColor: [41, 128, 185] },
      margin: { top: 110 }
    });

    const finalY = (doc as any).lastAutoTable.finalY || 150;

    // Totals
    const totalsX = pageWidth - 60;
    let ty = finalY + 10;
    
    doc.text('Subtotal:', totalsX, ty);
    doc.text(`$${quote.subtotal.toFixed(2)}`, pageWidth - 14, ty, { align: 'right' });
    
    if (quote.discountAmount > 0) {
      ty += 7;
      doc.text('Discount:', totalsX, ty);
      doc.text(`-$${quote.discountAmount.toFixed(2)}`, pageWidth - 14, ty, { align: 'right' });
    }

    if (quote.taxEnabled) {
      ty += 7;
      doc.text(`${quote.taxLabel} (${quote.taxRate}%):`, totalsX, ty);
      doc.text(`$${quote.taxAmount.toFixed(2)}`, pageWidth - 14, ty, { align: 'right' });
    }

    ty += 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Total:', totalsX, ty);
    doc.text(`$${quote.grandTotal.toFixed(2)}`, pageWidth - 14, ty, { align: 'right' });

    // Terms and Conditions
    if (quote.terms) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Terms & Conditions', 14, ty + 20);
      doc.setFont('helvetica', 'normal');
      const termsLines = doc.splitTextToSize(quote.terms, pageWidth - 28);
      doc.text(termsLines, 14, ty + 27);
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Quick Quote - Sales Representative: ${quote.salesRep}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

    doc.save(`Quote_${quote.number}_${quote.customer.name.replace(/\s+/g, '_')}.pdf`);
  }
};
